#ifndef __ARCH_PROTOCOL_SANDBOX_H
#define __ARCH_PROTOCOL_SANDBOX_H

#include <Protocol/LoadedImage.h>

#define EFI_SANDBOX_ARCH_PROTOCOL_GUID \
    { 0x7a31b274, 0x0e30, 0x4567, {0x9b, 0xb7, 0x04, 0x15, 0xf8, 0x28, 0xf9, 0xa9 }}

typedef struct _EFI_SANDBOX_ARCH_PROTOCOL EFI_SANDBOX_ARCH_PROTOCOL;

typedef struct {
    EFI_LOADED_IMAGE_PROTOCOL Info;
    EFI_IMAGE_ENTRY_POINT EntryPoint;
    EFI_HANDLE ImageHandle;
} EFI_SANDBOX_IMAGE_DATA;

typedef
EFI_STATUS
(EFIAPI *EFI_SANDBOX_CREATE_SANDBOX)(
    IN EFI_SANDBOX_ARCH_PROTOCOL *This,
    IN EFI_SANDBOX_IMAGE_DATA ImageData,
    OUT UINTN *SandboxID
);

typedef
EFI_STATUS
(EFIAPI *EFI_SANDBOX_START_SANDBOX)(
    IN EFI_SANDBOX_ARCH_PROTOCOL *This,
    IN EFI_HANDLE Handle,
    IN UINTN SandboxID
);

typedef
EFI_STATUS
(EFIAPI *EFI_SANDBOX_CLOSE_SANDBOX)(
    IN EFI_SANDBOX_ARCH_PROTOCOL *This,
    IN UINTN SandboxID
);

typedef
EFI_STATUS
(EFIAPI *EFI_SANDBOX_SCHEDULE_TO_SANDBOX)(
    IN EFI_SANDBOX_ARCH_PROTOCOL *This,
    IN OUT UINTN *SandboxID,
    IN BOOLEAN TplRaise
);

typedef
EFI_STATUS
(EFIAPI *EFI_SANDBOX_GET_CURRENT_SANDBOX_ID)(
    IN EFI_SANDBOX_ARCH_PROTOCOL *This,
    OUT UINTN *SandboxID
);

struct _EFI_SANDBOX_ARCH_PROTOCOL {
    EFI_SANDBOX_CREATE_SANDBOX CreateSandbox;
    EFI_SANDBOX_START_SANDBOX StartSandbox;
    EFI_SANDBOX_CLOSE_SANDBOX CloseSandbox;
    EFI_SANDBOX_SCHEDULE_TO_SANDBOX ScheduleToSandbox;
    EFI_SANDBOX_GET_CURRENT_SANDBOX_ID GetCurrentSandboxID;
    UINT64 UserAddressBase;
};

extern EFI_GUID gEfiSandboxArchProtocolGuid;

#endif
