#ifndef __BLOB_H__
#define __BLOB_H__

#include <Library/SandboxSyscalls.h>

#define C_SYS_BLOB_DECLARE(Name, ...)                                          \
  extern EFIAPI EFI_STATUS ASM_BLOB_##Name(__VA_ARGS__);                       \
  extern UINTN ASM_BLOB_##Name##_SIZE

#define C_SYS_BLOB_START(Name) ((VOID *)ASM_BLOB_##Name)
#define C_SYS_BLOB_SIZE(Name) ASM_BLOB_##Name##_SIZE

C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_RAISE_TPL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_RESTORE_TPL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_ALLOCATE_PAGES);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_FREE_PAGES);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_GET_MEMORY_MAP);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_ALLOCATE_POOL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_FREE_POOL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CREATE_EVENT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_SET_TIMER);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_WAIT_FOR_EVENT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_SIGNAL_EVENT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CLOSE_EVENT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CHECK_EVENT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_INSTALL_PROTOCOL_INTERFACE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_REINSTALL_PROTOCOL_INTERFACE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_UNINSTALL_PROTOCOL_INTERFACE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_HANDLE_PROTOCOL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_RESERVED);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_REGISTER_PROTOCOL_NOTIFY);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_LOCATE_HANDLE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_LOCATE_DEVICE_PATH);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_INSTALL_CONFIGURATION_TABLE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_IMAGE_LOAD);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_IMAGE_START);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_EXIT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_IMAGE_UNLOAD);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_EXIT_BOOT_SERVICES);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_GET_NEXT_MONOTONIC_COUNT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_STALL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_SET_WATCHDOG_TIMER);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CONNECT_CONTROLLER);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_DISCONNECT_CONTROLLER);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_OPEN_PROTOCOL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CLOSE_PROTOCOL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_OPEN_PROTOCOL_INFORMATION);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_PROTOCOLS_PER_HANDLE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_LOCATE_HANDLE_BUFFER);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_LOCATE_PROTOCOL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_INSTALL_MULTIPLE_PROTOCOL_INTERFACES);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_UNINSTALL_MULTIPLE_PROTOCOL_INTERFACES);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CALCULATE_CRC32);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_COPY_MEM);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_SET_MEM);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_BS_CREATE_EVENT_EX);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_GET_TIME);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_SET_TIME);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_GET_WAKEUP_TIME);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_SET_WAKEUP_TIME);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_SET_VIRTUAL_ADDRESS_MAP);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_CONVERT_POINTER);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_GET_VARIABLE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_GET_NEXT_VARIABLE_NAME);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_SET_VARIABLE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_GET_NEXT_HIGH_MONO_COUNT);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_RESET_SYSTEM);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_UPDATE_CAPSULE);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_QUERY_CAPSULE_CAPABILITIES);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_QUERY_VARIABLE_INFO);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_INTERFACE_CALL);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_RT_SANDBOX_RETURN);
C_SYS_BLOB_DECLARE(SANDBOX_SYS_NULL);

#endif
